### ISSUE TITLE
Add `from_optional` helper method to `Option`

### ISSUE THREAD

**Issue by rksouthee** [danielSanchezQ/rusty_results#19]
I've ran into a few scenarios where I need to convert from `typing.Optional[T]` to `rusty_results.Option[T]` and was wondering if we could add a helper function that would create an `Option[T]` from an `Optional[T]`, something like `Option[T].from_optional`.

**Comment by check69** [comment]
Nice suggestion, we will add this in the next version. Thanks!

**Comment by strinnityk** [comment]
Resolved with #20.
